version: 2

sphinx:
  builder: html
  configuration: docs/conf.py

formats:
  - pdf

python:
  version: "3.8"
  install:
    - method: pip
      path: .
      extra_requirements:
        - poetry
        - docs

