name: Build and test
on: push

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install tox and friends
        run: |
          pip install --upgrade pip tox poetry tox-poetry tox-docker

      - name: Cache tox environments
        uses: actions/cache@v2
        with:
          path: |
            .tox
            ~/.cache
            poetry.lock
          key: lint-${{ matrix.python }}-${{ hashFiles('**/pyproject.toml', '**/tox.ini') }}
          restore-keys: |
            lint-${{ matrix.python }}-${{ hashFiles('**/pyproject.toml', '**/tox.ini') }}

      - name: lint
        run: tox -e linters

  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox and friends
        run: |
          pip install --upgrade pip tox poetry tox-poetry tox-docker

      - name: Cache tox environments
        uses: actions/cache@v2
        with:
          path: |
            .tox
            ~/.cache
            poetry.lock
          key: ${{ matrix.python }}-${{ hashFiles('**/pyproject.toml', '**/tox.ini') }}
          restore-keys: |
            ${{ matrix.python }}-${{ hashFiles('**/pyproject.toml', '**/tox.ini') }}

      - name: run integration tests
        run: tox -e integrations

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions/cache@v2
        with:
          path: |
            .tox
            ~/.cache
            poetry.lock
          key: 3.7-${{ hashFiles('**/pyproject.toml', '**/tox.ini') }}
          restore-keys:
            3.7-${{ hashFiles('**/pyproject.toml', '**/tox.ini') }}
      - uses: snok/install-poetry@v1
        with:
          version: 1.1.8
          virtualenvs-create: false
          installer-parallel: true
      - name: Build docs
        run: |
          invoke build-docs
